### PR TITLE
Autorelease & Publish to PyPI

### LINKED ISSUE #823: Tag a new release since visdom is now under an open source license
Since #759 was resolved by relicensing visdom under the Apache 2.0 license, there has not been a new release. Since the relicensing was a significant change there should probably be a new release.

The folks involved in that relicensing were @lvdmaaten @JackUrb @mariobehling @fossasia, hopefully they can share the status of a new release.

PS: I suggest the dependabot PRs be merged before the release.

### PR DESCRIPTION
**Pull request by da-h**
## Description
This PR adds a github action to automate the release of visdom, both on github itself and PyPI.

## Motivation and Context
The goal of the implementation is to ensure a *low-maintenance release cycle* of the project.

**In more detail**:
- the action watches the `py/visdom/VERSON` file for changes on `master`
- whenever a new version occurs the action continues as follows (otherwise all the following steps are skipped)
- create a tag called `v$VERSION`
- create a release for that version  
  (in case the maintainer(s) of the project wishes to give more details, the API of the action allows to create a draft. changing the text, i.e. adding auto-generated release notes can be adapted afterwards).
- create a dist-file using `python setup.py` & publish the file using the official `pypa/gh-action-pypi-publish` action.

**Additionally**,
- this PR increases the version number (to `0.2`) to reflect the LICENCE change. (See []())
- this PR adapts the `PULL_REQUESTS_TEMPLATE.md` file to ask the contributors to increase the version numbers according to [semantic versioning](https://semver.org). (This is another suggestion based on the proposition of a low-maintenance PR-cycle. )

**Required before merging**:
**To enable automatic releases to PyPI and to ensure integrity of all releases, this PR requires to define a PyPI token secret inside this github-repository named `pypi_password`, visible only to repository maintainers.**

**Note**:
This PR closes #823.

## How Has This Been Tested?
See the example release in action in my fork.
- [the action outfile](https://github.com/da-h/visdom/runs/5630013063?check_suite_focus=true)
- [the created release](https://github.com/da-h/visdom/releases/tag/v0.2.0)
- [the created tag](https://github.com/da-h/visdom/tree/v0.2.0)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] For JavaScript changes, I have re-generated the minified JavaScript code.

### CODE REVIEW

**Comment by JackUrb** [comment]
Looking forward to having this kind of action set up! Let me look into generating a token and applying it here.

**Comment by JackUrb** [comment]
@mariobehling - In order to move forward with this, we'll need to add something to the secrets for this github, which I don't have permission to do. Is this something you can assist with?

**Comment by Soptq** [comment]
@JackUrb Any update about this?

**Comment by JackUrb** [comment]
I don't have the permissions for this unfortunately, I need someone in FOSSASIA to enable it for me first.

**Comment by da-h** [comment]
Since @mariobehling seems tied up right now and/or probably doesn't see the github messages, maybe do you know someone else who we can ping from the [fossasia-team](https://fossasia.org/team/) who could help us out?

**Comment by norbusan** [comment]
> Since @mariobehling seems tied up right now and/or probably doesn't see the github messages, maybe do you know someone else who we can ping from the [fossasia-team](https://fossasia.org/team/) who could help us out?

I just checked and I am in the same group as @JackUrb and I also don't see a way to add secrets. Seems that only Mario can do this. I will contact him.

**Comment by norbusan** [comment]
@da-h @JackUrb I have now full admin access, could you contact me (either here or in private) about what you specifically need?

**Comment by JackUrb** [comment]
> @da-h @JackUrb I have now full admin access, could you contact me (either here or in private) about what you specifically need?

I sent an email with details. Thanks for the help!

**Comment by da-h** [comment]
Just a side-note: I am unsure whether the version file should be changed in this very PR as well.
Probably we would want to have that in a separate PR to test things.

**Comment by JackUrb** [comment]
Agreed, we can do that on a second PR

**Comment by JackUrb** [comment]
OK The secret should be in now, should we try to do a deploy with this?

**Comment by da-h** [comment]
I have just proofread the workflow to be safe and found a small thing that could lead to bugs in the future.
(I did not prepend the `v` that is prepended before any tag when looking if a tag already exists).

In my opinion, the PR can now be merged; I have tested the current version of the workflow (up to the step of submitting to pypi) on my fork successfully.

**Pull request merged**
